
export const TWEET_CREATE_REQUEST = 'TWEET_CREATE_REQUEST';
export const TWEET_CREATE_SUCCESS = 'TWEET_CREATE_SUCCESS';
export const TWEET_CREATE_FAILURE = 'TWEET_CREATE_FAILURE';

export const TWEET_DELETE_REQUEST = 'TWEET_DELETE_REQUEST';
export const TWEET_DELETE_SUCCESS = 'TWEET_DELETE_SUCCESS';
export const TWEET_DELETE_FAILURE = 'TWEET_DELETE_FAILURE';

export const GET_ALL_TWEETS_REQUEST = 'GET_ALL_TWEETS_REQUEST';
export const GET_ALL_TWEETS_SUCCESS = 'GET_ALL_TWEETS_SUCCESS';
export const GET_ALL_TWEETS_FAILURE = 'GET_ALL_TWEETS_FAILURE';

export const GET_USERS_TWEET_REQUEST='GET_USERS_TWEET_REQUEST'
export const GET_USERS_TWEET_SUCCESS='GET_USERS_TWEET_SUCCESS'
export const GET_USERS_TWEET_FAILURE='GET_USERS_TWEET_FAILURE'

export const USER_LIKE_TWEET_REQUEST='USER_LIKE_TWEET_REQUEST';
export const USER_LIKE_TWEET_SUCCESS='USER_LIKE_TWEET_SUCCESS';
export const USER_LIKE_TWEET_FAILURE='USER_LIKE_TWEET_FAILURE';

export const LIKE_TWEET_REQUEST='LIKE_TWEET_REQUEST';
export const LIKE_TWEET_SUCCESS='LIKE_TWEET_SUCCESS';
export const LIKE_TWEET_FAILURE='LIKE_TWEET_FAILURE';

export const RETWEET_CREATE_REQUEST = 'RETWEET_CREATE_REQUEST';
export const RETWEET_CREATE_SUCCESS = 'RETWEET_CREATE_SUCCESS';
export const RETWEET_CREATE_FAILURE = 'RETWEET_CREATE_FAILURE';

export const FIND_TWEET_BY_ID_REQUEST = 'FIND_TWEET_BY_ID_REQUEST';
export const FIND_TWEET_BY_ID_SUCCESS = 'FIND_TWEET_BY_ID_SUCCESS';
export const FIND_TWEET_BY_ID_FAILURE = 'FIND_TWEET_BY_ID_FAILURE';


export const REPLY_TWEET_REQUEST = 'REPLY_TWEET_REQUEST';
export const REPLY_TWEET_SUCCESS = 'REPLY_TWEET_SUCCESS';
export const REPLY_TWEET_FAILURE = 'REPLY_TWEET_FAILURE';


export const VIEW_PLUS_REQUEST = 'VIEW_PLUS_REQUEST';
export const VIEW_PLUS_SUCCESS = 'VIEW_PLUS_SUCCESS';
export const VIEW_PLUS_FAILURE = 'VIEW_PLUS_FAILURE';

export const UPDATE_TWEET_REQUEST='UPDATE_TWEET_REQUEST';
export const UPDATE_TWEET_SUCCESS='UPDATE_TWEET_SUCCESS';
export const UPDATE_TWEET_FAILURE = 'UPDATE_TWEET_FAILURE';

export const FOLLOW_TWIT_FAILURE='FOLLOW_TWIT_FAILURE';
export const FOLLOW_TWIT_REQUEST='FOLLOW_TWIT_REQUEST';
export const FOLLOW_TWIT_SUCCESS='FOLLOW_TWIT_SUCCESS';

export const GET_USERS_REPLIES_REQUEST='GET_USERS_REPLIES_REQUEST';
export const GET_USERS_REPLIES_SUCCESS='GET_USERS_REPLIES_SUCCESS';
export const GET_USERS_REPLIES_FAILURE='GET_USERS_REPLIES_FAILURE';