export const NOTIFICATION_PLUS_REQUEST = 'NOTIFICATION_PLUS_REQUEST';
export const NOTIFICATION_PLUS_SUCCESS = 'NOTIFICATION_PLUS_SUCCESS';
export const NOTIFICATION_PLUS_FAILURE = 'NOTIFICATION_PLUS_FAILURE';