export const COM_CREATE_REQUEST = 'COM_CREATE_REQUEST';
export const COM_CREATE_SUCCESS = 'COM_CREATE_SUCCESS';
export const COM_CREATE_FAILURE = 'COM_CREATE_FAILURE';

export const GET_COMS_REQUEST = 'GET_COMS_REQUEST';
export const GET_COMS_SUCCESS = 'GET_COMS_SUCCESS';
export const GET_COMS_FAILURE = 'GET_COMS_FAILURE';

export const UPDATE_COM_REQUEST = 'UPDATE_COM_REQUEST';
export const UPDATE_COM_SUCCESS = 'UPDATE_COM_SUCCESS';
export const UPDATE_COM_FAILURE = 'UPDATE_COM_FAILURE';

export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const FIND_COM_BY_ID_REQUEST='FIND_COM_BY_ID_REQUEST';
export const FIND_COM_BY_ID_SUCCESS='FIND_COM_BY_ID_SUCCESS';
export const FIND_COM_BY_ID_FAILURE='FIND_COM_BY_ID_FAILURE';


export const ADD_USER_SIGNUP_REQUEST= 'ADD_USER_SIGNUP_REQUEST';
export const ADD_USER_SIGNUP_SUCCESS= 'ADD_USER_SIGNUP_SUCCESS';
export const ADD_USER_SIGNUP_FAILURE='ADD_USER_SIGNUP_FAILURE';

export const REMOVE_FOLLOW_REQUEST='REMOVE_FOLLOW_REQUEST';
export const REMOVE_FOLLOW_SUCCESS='REMOVE_FOLLOW_SUCCESS';
export const REMOVE_FOLLOW_FAILURE='REMOVE_FOLLOW_FAILURE';