export const COM_CREATE_REQUEST='COM_CREATE_REQUEST';
export const COM_CREATE_SUCCESS='COM_CREATE_SUCCESS';
export const COM_CREATE_FAILURE='COM_CREATE_FAILURE';

export const GET_COMS_REQUEST='GET_COMS_REQUEST';
export const GET_COMS_SUCCESS='GET_COMS_SUCCESS';
export const GET_COMS_FAILURE='GET_COMS_FAILURE';