export const COM_CREATE_REQUEST = 'COM_CREATE_REQUEST';
export const COM_CREATE_SUCCESS = 'COM_CREATE_SUCCESS';
export const COM_CREATE_FAILURE = 'COM_CREATE_FAILURE';

export const GET_COMS_REQUEST = 'GET_COMS_REQUEST';
export const GET_COMS_SUCCESS = 'GET_COMS_SUCCESS';
export const GET_COMS_FAILURE = 'GET_COMS_FAILURE';


export const UPDATE_COM_REQUEST = 'UPDATE_COM_REQUEST';
export const UPDATE_COM_SUCCESS = 'UPDATE_COM_SUCCESS';
export const UPDATE_COM_FAILURE = 'UPDATE_COM_FAILURE';

export const ADD_USER_REQUEST='ADD_USER_REQUEST';
export const ADD_USER_SUCCESS='ADD_USER_SUCCESS';
export const ADD_USER_FAILURE='ADD_USER_FAILURE';

export const GET_USER_REQUEST='GET_USER_REQUEST';
export const GET_USER_SUCCESS='GET_USER_SUCCESS';
export const GET_USER_FAILURE='GET_USER_FAILURE';