# Generated by Django 4.2.3 on 2023-09-12 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('image_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('profile_dir', models.ImageField(upload_to='')),
                ('profile_url', models.URLField(null=True)),
                ('write_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('write_id', models.CharField(max_length=50)),
            ],
        ),
    ]
